// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using MDMQ.ImpuestoTributario.Patentes.Datos.Models;
using Microsoft.EntityFrameworkCore;

namespace MDMQ.ImpuestoTributario.Patentes.Datos.Contexts;

public partial class MDMQ_CORE_TRIBUTARIOContext : DbContext
{
    public MDMQ_CORE_TRIBUTARIOContext(DbContextOptions<MDMQ_CORE_TRIBUTARIOContext> options)
        : base(options)
    {
    }

    public virtual DbSet<CorBeneficioTributario> CorBeneficioTributario { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<CorBeneficioTributario>(entity =>
        {
            entity.HasKey(e => e.BeneficioTributarioId);

            entity.ToTable("COR_BENEFICIO_TRIBUTARIO", "CORE");

            entity.Property(e => e.BeneficioTributarioId).HasColumnName("BENEFICIO_TRIBUTARIO_ID");
            entity.Property(e => e.Estado)
                .HasMaxLength(5)
                .IsUnicode(false)
                .HasColumnName("ESTADO");
            entity.Property(e => e.FechaActualizacion)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_ACTUALIZACION");
            entity.Property(e => e.FechaRegistro)
                .HasColumnType("datetime")
                .HasColumnName("FECHA_REGISTRO");
            entity.Property(e => e.NumeroIdentificacion)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("NUMERO_IDENTIFICACION");
            entity.Property(e => e.Path)
                .IsRequired()
                .IsUnicode(false)
                .HasColumnName("PATH");
            entity.Property(e => e.RazonSocial)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("RAZON_SOCIAL");
            entity.Property(e => e.TipoCertificadoId).HasColumnName("TIPO_CERTIFICADO_ID");
            entity.Property(e => e.TipoEmpresaId).HasColumnName("TIPO_EMPRESA_ID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}