// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MDMQ.ImpuestoTributario.Patentes.Datos.Models-Temp;

public partial class CorBeneficioTributario
{
    public int BeneficioTributarioId { get; set; }

    public string NumeroIdentificacion { get; set; }

    public string RazonSocial { get; set; }

    public int TipoEmpresaId { get; set; }

    public int TipoCertificadoId { get; set; }

    public DateTime FechaRegistro { get; set; }

    public string Estado { get; set; }

    public DateTime FechaActualizacion { get; set; }

    public string Path { get; set; }
}