// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MDMQ.ImpuestoTributario.Patentes.Datos.Models-Temp;

/// <summary>
/// Tabla que contiene los catálogos a utilizar
/// </summary>
public partial class CorTdCatalogo
{
    /// <summary>
    /// Identificador único del registro
    /// </summary>
    public int CorTdCatalogoId { get; set; }

    /// <summary>
    /// Código del nivel al que pertenece el catálogo
    /// </summary>
    public int? CatalogoPadre { get; set; }

    /// <summary>
    /// Código propio del catálogo
    /// </summary>
    public int? CatalogoHijo { get; set; }

    /// <summary>
    /// Nombre del catálogo
    /// </summary>
    public string Descripcion { get; set; }

    /// <summary>
    /// Código propio del catálogo
    /// </summary>
    public string CodigoNegocio { get; set; }

    /// <summary>
    /// Número de nivel del catálogo
    /// </summary>
    public int? Nivel { get; set; }

    /// <summary>
    /// 1=si está vigente, 0=no
    /// </summary>
    public bool? Vigente { get; set; }

    /// <summary>
    /// Valor alfanumérico
    /// </summary>
    public string Parametro1 { get; set; }

    /// <summary>
    /// Valor entero
    /// </summary>
    public int? Parametro2 { get; set; }

    /// <summary>
    /// Valor decimal
    /// </summary>
    public decimal? Parametro3 { get; set; }

    /// <summary>
    /// Fecha de creación del registro
    /// </summary>
    public DateTime? FechaCreacion { get; set; }

    /// <summary>
    /// Identificador del usuario que crea el registro
    /// </summary>
    public int? UsuarioCreacion { get; set; }

    /// <summary>
    /// Fecha de modificación del registro
    /// </summary>
    public DateTime? FechaModificacion { get; set; }

    /// <summary>
    /// Identificador del usuario que modifica el registro
    /// </summary>
    public int? UsuarioModificacion { get; set; }

    public DateTime? Parametro4 { get; set; }
}