// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MDMQ.ImpuestoTributario.Patentes.Datos.Models;

/// <summary>
/// Tabla que almacena los datos del contribuyente extraídos del SRi
/// </summary>
public partial class CorCatastroSri
{
    /// <summary>
    /// Número de RUC del contribuyente
    /// </summary>
    public string NumeroRuc { get; set; }

    /// <summary>
    /// Número de identificación del contribuyente (RUC o Cédula)
    /// </summary>
    public string NumeroIdentificacion { get; set; }

    /// <summary>
    /// Referencia al identificador único del registro de la Clase de Contribuyente
    /// </summary>
    public string ClaseContribuyenteId { get; set; }

    /// <summary>
    /// Referencia al identificador único del registro de la Actividad Económica
    /// </summary>
    public string ActividadEconomicaId { get; set; }

    /// <summary>
    /// Referencia al identificador único del registro del Código de Identificación Municipal
    /// </summary>
    public long? PersonaId { get; set; }

    /// <summary>
    /// Tipo de contribuyente (Persona o Sociedad)
    /// </summary>
    public string TipoContribuyente { get; set; }

    /// <summary>
    /// Sub tipo de contribuyente (Tipo de Contribuyente)
    /// </summary>
    public string GrupoContribuyente { get; set; }

    /// <summary>
    /// Indica si el contribuyente está obligado a llevar contabilidad
    /// </summary>
    public string Obligado { get; set; }

    /// <summary>
    /// Número de identificación del Contador
    /// </summary>
    public string RucContador { get; set; }

    /// <summary>
    /// Número de cédula del Reqpresentante Legal
    /// </summary>
    public string IdentificacionRepresentanteLegal { get; set; }

    /// <summary>
    /// Cargo del Representante Legal
    /// </summary>
    public string CargoRepresentanteLegal { get; set; }

    /// <summary>
    /// Fecha de Inscripción del RUC
    /// </summary>
    public DateOnly? FechaInscripcion { get; set; }

    /// <summary>
    /// Fecha de Inicio de Actividades
    /// </summary>
    public DateOnly? FechaInicioActividades { get; set; }

    /// <summary>
    /// Fecha de Constitución de la empresa
    /// </summary>
    public DateOnly? FechaConstitucion { get; set; }

    /// <summary>
    /// Fecha de Reinicio de Actividades
    /// </summary>
    public DateOnly? FechaReinicioActividades { get; set; }

    /// <summary>
    /// Fecha de Suspensión Definitiva
    /// </summary>
    public DateOnly? FechaSuspensionDefinitiva { get; set; }

    /// <summary>
    /// Estado del contribuyente en el SRi
    /// </summary>
    public string Estado { get; set; }

    /// <summary>
    /// Estado de la Sociedad (Sector Popular y Solidario)
    /// </summary>
    public string EstadoSociedad { get; set; }

    /// <summary>
    /// Estado Legal de la Compañía
    /// </summary>
    public string EstadoLegalCompania { get; set; }

    /// <summary>
    /// Fecha del Registro
    /// </summary>
    public DateOnly FechaRegistro { get; set; }

    /// <summary>
    /// Fecha y Hora del Registro
    /// </summary>
    public DateTime FechaHoraRegistro { get; set; }

    /// <summary>
    /// Usuario que realizó el Registro
    /// </summary>
    public string UsuarioRegistro { get; set; }

    /// <summary>
    /// Terminal (equipo) desde donde se realizó el Registro (IPv4 o IPv6)
    /// </summary>
    public string TerminalRegistro { get; set; }

    /// <summary>
    /// Fecha de la Última Actualización
    /// </summary>
    public DateOnly? FechaActualizacion { get; set; }

    /// <summary>
    /// Fecha y Hora de la Última Actualización
    /// </summary>
    public DateTime? FechaHoraActualizacion { get; set; }

    /// <summary>
    /// Usuario que realizó la Última Actualización
    /// </summary>
    public string UsuarioActualizacion { get; set; }

    /// <summary>
    /// Terminal (equipo) desde donde se realizó la Última Actualización (IPv4 o IPv6)
    /// </summary>
    public string TerminalActualizacion { get; set; }

    public string RazonSocial { get; set; }

    public decimal? CodigoPersonaSri { get; set; }

    public decimal? CodigoPersonaRelacionadaSri { get; set; }

    public string NombreRepresentanteLegal { get; set; }

    public string CallePrincipal { get; set; }

    public string NumeroCasa { get; set; }

    public string Interseccion { get; set; }

    public string CodigoUbicacionGeograficaProvincia { get; set; }

    public string CodigoUbicacionGeograficaCanton { get; set; }

    public string CodigoUbicacionGeograficaParroquia { get; set; }

    public string Barrio { get; set; }

    public string EmailPrincipal { get; set; }

    public string TelefonoCelular { get; set; }

    public string TelefonoConvencional { get; set; }

    public string CargaInicial { get; set; }

    public string DescripcionEstadoContribuyente { get; set; }

    public DateOnly? FechaNombramiento { get; set; }

    public string Referencia { get; set; }
}